# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Pfppgq67Yz2ZKeRof00FAH6XVpvCjY-
"""

!pip install pyspark

# ===================================================================================================
# FOLDER REPOSITORY : Global-Banking-Fraud-Isolation-Engine
# FILE NAME         : generate_test_data.py
# AUTHOR            : Sk Saiful Inam (Senior Data Lead)
# DESCRIPTION       : Generates the external raw transaction file for testing dynamic variables
# ===================================================================================================
import pandas as pd

payload = {
    "transaction_id": ["TXN101", "TXN102", "TXN103", "TXN103"],
    "account_number": ["ACC9001", "ACC9002", "ACC9003", "ACC9003"],
    "transaction_date": ["2026-09-09", "2026-09-11", "2026-09-11", "2026-09-11"],
    "transaction_amount": [5000.00, 125000.00, 450.00, 450.00],
    "fraud_risk_score": [0.12, 0.95, 0.05, 0.05],
    "last_updated": ["2026-09-09 09:00:00", "2026-09-11 10:15:00", "2026-09-11 11:30:00", "2026-09-11 11:45:00"]
}

df = pd.DataFrame(payload)
df.to_csv("daily_ledger.csv", index=False)
print(">>> SUCCESS: External 'daily_ledger.csv' file has been physically created on the server environment! <<<")

# ===================================================================================================
# FOLDER REPOSITORY : Global-Banking-Fraud-Isolation-Engine
# FILE NAME         : pipeline_validation_engine.py
# AUTHOR            : Sk Saiful Inam (Senior Data Lead)
# DESCRIPTION       : Production ETL engine calculating watermarks dynamically from target layers
# ===================================================================================================
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max, row_number
from pyspark.sql.window import Window

print("\n===================================================================================")
print(">>> INITIALIZING FULLY AUTOMATED SYSTEM RUN: SK SAIFUL INAM (SENIOR DATA LEAD) <<<")
print("===================================================================================\n")

# 1. BOOT UP THE PARALLEL COMPUTE ENGINE SPARK SESSION
spark = SparkSession.builder.appName("AutomatedWatermarkEngine").getOrCreate()

# 2. SIMULATE TARGET WAREHOUSE LAYER (What is already loaded inside the bank database)
# Let's assume the database already has historical data up to 2026-09-10
warehouse_mock_data = [("TXN099", "ACC1001", "2026-09-10", 120.00, 0.01, "2026-09-10 18:00:00")]
warehouse_schema = ["transaction_id", "account_number", "transaction_date", "transaction_amount", "fraud_risk_score", "last_updated"]
target_warehouse_df = spark.createDataFrame(warehouse_mock_data, warehouse_schema)

# ===================================================================================================
# AUTOMATED VARIABLE LOOKUP CORE: We query the target table to find the highest date in memory
# ===================================================================================================
automated_max_record = target_warehouse_df.select(max("transaction_date")).collect()
DYNAMIC_WATERMARK_DATE = automated_max_record[0][0]

print(f"[STAGE 1] TARGET AUDIT COMPLETE: Highest loaded date found in Warehouse: {DYNAMIC_WATERMARK_DATE}")
print(f"[STAGE 2] INGESTION LOOKUP: Ingestion engine will now pull records strictly greater than {DYNAMIC_WATERMARK_DATE}\n")

# 3. DYNAMICALLY LOAD THE NEW INCOMING DATA FILE FROM S3/DISK
INPUT_FILE_PATH = "daily_ledger.csv"
raw_file_df = spark.read.option("header", "true").option("inferSchema", "true").csv(INPUT_FILE_PATH)

# 4. RUN CHANGE DATA CAPTURE (CDC) FILTER USING THE AUTOMATED VARIABLE
incremental_delta_df = raw_file_df.filter(col("transaction_date") > DYNAMIC_WATERMARK_DATE)
print(f"[STAGE 3] CDC complete. Extracted new delta records based on automated watermark.")

# 5. RUN ANALYTICAL WINDOW DEDUPLICATION
transaction_window = Window.partitionBy("transaction_id").orderBy(col("last_updated").desc())
deduplicated_df = incremental_delta_df.withColumn(
    "row_num", row_number().over(transaction_window)
).filter(col("row_num") == 1).drop("row_num")
print("[STAGE 4] Stale duplicate transaction payloads purged from Spark memory partitions.")

# 6. RUN RISK SEPARATION & ROUTING RULES
quarantine_filter = (col("fraud_risk_score") > 0.90) | (col("account_number").isNull())
quarantine_df = deduplicated_df.filter(quarantine_filter)
clean_banking_df = deduplicated_df.filter(~quarantine_filter)

print("\n -> SECURITY QUARANTINE ROUTE ISOLATION OUTPUT:")
quarantine_df.select("transaction_id", "account_number", "transaction_amount", "fraud_risk_score").show()

print(" -> TARGET ANALYTICAL SILVER ZONE UPDATE OUTPUT:")
clean_banking_df.select("transaction_id", "account_number", "transaction_amount", "fraud_risk_score").show()

print("===================================================================================")
print(">>> AUTOMATED DATA PIPELINE SUCCESSFULLY EXECUTED BY AUTHOR: SK SAIFUL INAM <<<")
print("===================================================================================\n")

# ===================================================================================================
# FOLDER REPOSITORY : Global-Banking-Fraud-Isolation-Engine
# FILE NAME         : pipeline_validation_engine.py
# AUTHOR            : Sk Saiful Inam (Senior Data Lead)
# DESCRIPTION       : Dynamic validation engine running CDC and risk queries via variables
# ===================================================================================================
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max, row_number
from pyspark.sql.window import Window

print("\n===================================================================================")
print(">>> RUNNING DYNAMIC RUNTIME ENGINE: SK SAIFUL INAM (SENIOR DATA LEAD) <<<")
print("===================================================================================\n")

# 1. INITIALIZE CLUSTER INPUT VARIABLES
INPUT_FILE_PATH = "daily_ledger.csv"
WATERMARK_DATE_VARIABLE = "2026-09-10"

# 2. BOOT UP SPARK SERVICE SESSION
spark = SparkSession.builder.appName("DynamicBankingIsolation").getOrCreate()
print(f"[STAGE 1] Spark Session Connected. Targeted Input File: {INPUT_FILE_PATH}")

# 3. DYNAMICALLY INGEST SOURCE FILE ROWS
raw_file_df = spark.read.option("header", "true").option("inferSchema", "true").csv(INPUT_FILE_PATH)
print(f"[STAGE 2] Loaded file structure successfully. Total raw input rows: {raw_file_df.count()}")

# 4. EXECUTE CHANGE DATA CAPTURE QUERY USING DYNAMIC VARIABLE
incremental_delta_df = raw_file_df.filter(col("transaction_date") > WATERMARK_DATE_VARIABLE)
print(f"[STAGE 3] CDC complete using variable threshold (> {WATERMARK_DATE_VARIABLE}). Outdated rows pruned.")

# 5. EXECUTE ANALYTICAL WINDOW DEDUPLICATION
transaction_window = Window.partitionBy("transaction_id").orderBy(col("last_updated").desc())
deduplicated_df = incremental_delta_df.withColumn(
    "row_num", row_number().over(transaction_window)
).filter(col("row_num") == 1).drop("row_num")
print("[STAGE 4] Analytical window metrics calculated. Duplicate transaction hashes removed.")

# 6. EXECUTE RISK SEPARATION & ROUTING RULES
quarantine_filter = (col("fraud_risk_score") > 0.90) | (col("account_number").isNull())
quarantine_df = deduplicated_df.filter(quarantine_filter)
clean_banking_df = deduplicated_df.filter(~quarantine_filter)

print("\n -> DYNAMIC QUARANTINE SECURITY ISOLATION OUTPUT:")
quarantine_df.select("transaction_id", "account_number", "transaction_amount", "fraud_risk_score").show()

print(" -> DYNAMIC ANALYTICAL SILVER ZONE TARGET UPDATE OUTPUT:")
clean_banking_df.select("transaction_id", "account_number", "transaction_amount", "fraud_risk_score").show()

print("===================================================================================")
print(">>> DYNAMIC PRODUCTION CODE SIMULATION COMPLETED BY AUTHOR: SK SAIFUL INAM <<<")
print("===================================================================================\n")